version: "3.8"

services:
  streamlit:
    build:
      context: ./
      dockerfile: Dockerfile.ui
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
  api:
    build:
      context: ./
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    
    
    # env_file:
    #   - .env
    
